-- Create user and grant permissions
CREATE USER poc_user IDENTIFIED BY poc_password;
GRANT CONNECT, RESOURCE, DBA TO poc_user;
GRANT UNLIMITED TABLESPACE TO poc_user;

-- Connect as poc_user
CONNECT poc_user/poc_password@XE;

-- Create tables
CREATE TABLE ui_customizations (
                                   user_id VARCHAR2(255) PRIMARY KEY,
                                   profile_name VARCHAR2(500) NOT NULL,
                                   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   version VARCHAR2(255) NOT NULL
);

CREATE TABLE ui_components (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id VARCHAR2(255) NOT NULL,
                               component_id VARCHAR2(255) NOT NULL,
                               component_type VARCHAR2(100) NOT NULL,
                               name VARCHAR2(500) NOT NULL,
                               display_order NUMBER NOT NULL,
                               visible NUMBER(1) DEFAULT 1,
                               properties CLOB,
                               last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT fk_components_user FOREIGN KEY (user_id) REFERENCES ui_customizations(user_id) ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX idx_components_user_id ON ui_components(user_id);
CREATE INDEX idx_components_type_user ON ui_components(component_type, user_id);
CREATE INDEX idx_components_order ON ui_components(user_id, display_order);

-- Insert sample data
INSERT INTO ui_customizations (user_id, profile_name, version) VALUES ('demo_user', 'Demo Profile', 'v1');

INSERT INTO ui_components (user_id, component_id, component_type, name, display_order, visible, properties) VALUES
                                                                                                                ('demo_user', 'header_1', 'HEADER', 'Main Header', 1, 1, '{"color": "#ffffff", "height": 60}'),
                                                                                                                ('demo_user', 'sidebar_1', 'SIDEBAR', 'Navigation Sidebar', 2, 1, '{"width": 250, "theme": "dark"}'),
                                                                                                                ('demo_user', 'widget_1', 'WIDGET', 'Dashboard Widget', 3, 1, '{"type": "chart", "data": "sales"}');

COMMIT;
